const LOGIN_STARTED = "LOGIN_STARTED";
const TODO_ADDED = "TODO_ADDED";
const TODO_TOGGLED = "TODO_TOGGLED";
const TODO_REMOVE_COMPLETED = "TODO_REMOVE_COMPLETED";
const LOGOUT_STARTED = "LOGOUT_STARTED";
const CHANGE_TABS = "CHANGE_TABS";
export const types = {
  TODO_REMOVE_COMPLETED,
  TODO_TOGGLED,
  TODO_ADDED,
  LOGIN_STARTED,
  LOGOUT_STARTED,
  CHANGE_TABS,
};
