const LOGIN_STARTED = "LOGIN_STARTED";
const LOGIN_COMPLETED = "LOGIN_COMPLETED";
const LOGIN_ERROR = "LOGIN_ERROR";

const types = {
  LOGIN_STARTED,
  LOGIN_COMPLETED,
  LOGIN_ERROR,
};

export default types;
