const NOTES_FETCH = "NOTES_FETCH";
const NOTES_FETCHED = "NOTES_FETCHED";
const NOTES_ERROR = "NOTES_ERROR";

const NOTE_CREATION_RESET = "NOTE_CREATION_RESET";
const NOTE_CREATE = "NOTE_CREATE";
const NOTE_CREATED = "NOTE_CREATED";
const NOTE_CREATE_ERROR = "NOTE_CREATE_ERROR";

const types = {
  NOTES_FETCH,
  NOTES_FETCHED,
  NOTES_ERROR,
  NOTE_CREATE,
  NOTE_CREATED,
  NOTE_CREATE_ERROR,
  NOTE_CREATION_RESET,
};

export default types